AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  edu-rpa-serverless-robot

  Sample SAM Template for edu-rpa-serverless-robot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  RobotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
        -
          AttributeName: processIdVersion
          KeyType: RANGE
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: N
        -
          AttributeName: processIdVersion
          AttributeType: S
        -
          AttributeName: launchTime
          AttributeType: S
        -
          AttributeName: instanceId
          AttributeType: S
        -
          AttributeName: state
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: robot

  RobotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: robot
    DeletionPolicy: Retain

  RobotHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  RunRobotFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectRobotTable:
        Properties:
          Destination:
            Id: RobotTable
          Permissions:
            - Write
    Properties:
      PackageType: Zip
      CodeUri: src/robot/
      Handler: app.run_robot
      Runtime: python3.9
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /robot/run
            Method: POST
            ApiId: !Ref RobotHttpApi

  StopRobotFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectRobotTable:
        Properties:
          Destination:
            Id: RobotTable
          Permissions:
            - Write
    Properties:
      PackageType: Zip
      CodeUri: src/robot/
      Handler: app.stop_robot
      Runtime: python3.9
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /robot/stop
            Method: POST
            ApiId: !Ref RobotHttpApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RobotHttpApi:
    Description: Serverless HTTP API (API Gateway endpoint URL)
    Value: !Sub "https://${RobotHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
