AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  edu-rpa-serverless-robot

  Sample SAM Template for edu-rpa-serverless-robot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  RobotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
        -
          AttributeName: processIdVersion
          KeyType: RANGE
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: S
        -
          AttributeName: processIdVersion
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: robot

  RobotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: edu-rpa-robot
    DeletionPolicy: Retain

  RobotHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  RunRobotFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectRobotTable:
        Properties:
          Destination:
            Id: RobotTable
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Zip
      CodeUri: src/robot/
      Handler: app.run_robot
      Runtime: python3.9
      Policies:
        - Statement:
          - Effect: Allow
            Action: 'iam:PassRole'
            Resource: 'arn:aws:iam::678601387840:role/EC2_robot_role'
          - Effect: Allow
            Action: 
              - 'ec2:RunInstances'
              - 'ec2:CreateTags'
            Resource: '*'
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /robot/run
            Method: POST
            ApiId: !Ref RobotHttpApi

  StopRobotFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectRobotTable:
        Properties:
          Destination:
            Id: RobotTable
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Zip
      CodeUri: src/robot/
      Handler: app.stop_robot
      Runtime: python3.9
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - 'ec2:StopInstances'
            Resource: '*'
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /robot/stop
            Method: POST
            ApiId: !Ref RobotHttpApi

  GetRobotDetailFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectRobotTable:
        Properties:
          Destination:
            Id: RobotTable
          Permissions:
            - Read
    Properties:
      PackageType: Zip
      CodeUri: src/robot/
      Handler: app.get_robot_detail
      Runtime: python3.9
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /robot/detail
            Method: GET
            ApiId: !Ref RobotHttpApi

  UpdateRobotStateFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectRobotTable:
        Properties:
          Destination:
            Id: RobotTable
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Zip
      CodeUri: src/robot/
      Handler: app.update_robot_state
      Runtime: python3.9
      Policies:
        - Statement:
          - Effect: Allow
            Action: 'ec2:DescribeInstances'
            Resource: '*'
      Events:
        EC2EBRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification
            Target:
              Id: UpdateRobotStateFunction
            RuleName: EC2-robot-instance-updates-state

  CreateScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: src/schedule/
      Handler: app.create_schedule
      Runtime: python3.9
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - 'scheduler:GetSchedule'
              - 'scheduler:CreateSchedule'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource: 'arn:aws:iam::678601387840:role/Robot_Scheduler_Role'
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /schedule
            Method: POST
            ApiId: !Ref RobotHttpApi

  DeleteScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: src/schedule/
      Handler: app.delete_schedule
      Runtime: python3.9
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - 'scheduler:DeleteSchedule'
            Resource: '*'
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /schedule/delete
            Method: POST
            ApiId: !Ref RobotHttpApi

  GetScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: src/schedule/
      Handler: app.get_schedule
      Runtime: python3.9
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - 'scheduler:GetSchedule'
            Resource: '*'
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /schedule
            Method: GET
            ApiId: !Ref RobotHttpApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RobotHttpApi:
    Description: Serverless HTTP API (API Gateway endpoint URL)
    Value: !Sub "https://${RobotHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
